export { accessibility } from './Split.demo.accessibility';
export { configurator } from './Split.demo.configurator';
export { doubleclick } from './Split.demo.doubleclick';
export { events } from './Split.demo.events';
export { gradient } from './Split.demo.gradient';
export { growFirst, growHorizontal, growSecond, growThreePanes } from './Split.demo.grow';
export { initials } from './Split.demo.initials';
export { inline } from './Split.demo.inline';
export { max } from './Split.demo.max';
export { multiple } from './Split.demo.multiple';
export { nested } from './Split.demo.nested';
export { nestedprops } from './Split.demo.nestedprops';
export { pane } from './Split.demo.pane';
export { reset } from './Split.demo.reset';
export { resizer } from './Split.demo.resizer';
export { resizerEvents } from './Split.demo.resizerEvents';
export { store } from './Split.demo.store';
